name = "Vulpinian Skies"
author = "Ahri_Loyala"
version = "1.0b5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "005db6f49330f5f7f3d61c2852e0c31f534e2626c1e1ab0a818c80b1e8b25887"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
