name = "Vulpinian Skies"
author = "Ahri_Loyala"
version = "1.0b2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c0cb883c09dc301d0315cd51c5a112f176fc49691cd0303f38aac840e2925cb"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
