name = "Vulpinian Skies"
author = "Aurora_Luciri (Fox)"
version = "1.0b11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "391c1f1060ea2314c5d53408c9048264f0c9ccf49ae41f90030989ee6bb8b15c"

[versions]
forge = "40.2.4"
minecraft = "1.18.2"
