name = "Vulpinian Skies"
author = "Aurora_Luciri (Fox)"
version = "1.0b9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "53a2fb461fb998ae39bb8d824207d3a8d1e44a53775f5de0f123ad32ab926dff"

[versions]
forge = "40.2.4"
minecraft = "1.18.2"
