name = "Vulpinian Skies"
author = "Aurora_Luciri (Fox)"
version = "1.0b9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d863319a51e2270267474ee9a21f08ee0266bd5c137a6255aec797231a9b098"

[versions]
forge = "40.2.4"
minecraft = "1.18.2"
