name = "Vulpinian Skies"
author = "Aurora_Luciri (Fox)"
version = "1.0b13-PR2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71abbe97bccc93bef0870a5fd26caa0a577edddb0a6b36076b61dc4f071c74ce"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
