name = "Vulpinian Skies"
author = "Aurora_Luciri (Fox)"
version = "1.0b8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd2f66e33d16689defb5c163a9e2183ff31db3bba159c3d38ab3e8ba240f9167"

[versions]
forge = "40.2.4"
minecraft = "1.18.2"
