name = "Vulpinian Skies"
author = "Aurora_Luciri (Fox)"
version = "1.0b13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebacc1d6441aa1877122148afb410ffa6f9514368ab9564c9d797fbc32758eab"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
