name = "Vulpinian Skies"
author = "Aurora_Luciri (Fox)"
version = "1.0b9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63345871e8fcb3f3fdaee8f11668773f564c37a10312f78778acba8e2a96fec4"

[versions]
forge = "40.2.4"
minecraft = "1.18.2"
