name = "Vulpinian Skies"
author = "Aurora_Luciri (Fox)"
version = "1.0b11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c058d60a6fd2e007633c4ff86056eaf116800ec89f167b5de8b880297320b3f"

[versions]
forge = "40.2.4"
minecraft = "1.18.2"
