name = "Vulpinian Skies"
author = "Aurora_Luciri (Fox)"
version = "1.0b9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14788c069598f70278a950ce0c5bea8632ea5775e30d7e9bca2d929c9240ec58"

[versions]
forge = "40.2.4"
minecraft = "1.18.2"
