name = "Vulpinian Skies"
author = "Aurora_Luciri (Fox)"
version = "1.0b9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "178452724db3386695ca41ccdea5fd2fee221f25374c4eb0e950772b210882a4"

[versions]
forge = "40.2.4"
minecraft = "1.18.2"
